# DUMMY
import logging
from typing import List

logger = logging.getLogger(__name__)

from app.models.route_models import Route
from app.models.document_models import Document, DocumentType, GenerateDocumentsRequest


def _extract_sections(markdown: str) -> List[str]:
    """Extract heading text from Markdown content."""
    import re
    return re.findall(r"^#{1,3}\s+(.+)$", markdown, re.MULTILINE)


async def generate_document(doc_type: DocumentType, route: Route) -> Document:
    """Generate a dummy document for the given route and document type."""
    
    dummy_content = f"""# {doc_type.value.title()} Document

This is a placeholder document for {doc_type.value}.

## Route Information
- Route ID: {route.id if hasattr(route, 'id') else 'Unknown'}
- Target Molecule: {route.target_smiles if hasattr(route, 'target_smiles') else 'Unknown'}

## Summary
This is a dummy document generated as a placeholder. The actual AI-powered document generation has been disabled.

## Notes
- This is a template document
- Real content would be generated by AI service
- All sections are placeholders for demonstration purposes

## Disclaimer
This document is for demonstration purposes only and should not be used for actual pharmaceutical manufacturing or regulatory submissions.
"""
    
    sections = _extract_sections(dummy_content)
    
    return Document(
        type=doc_type,
        title=f"{doc_type.value.title()} Document (Dummy)",
        content=dummy_content,
        sections=sections,
    )


async def generate_documents(request: GenerateDocumentsRequest) -> List[Document]:
    """Generate dummy documents for the requested types."""
    import asyncio
    
    tasks = [generate_document(doc_type, request.route) for doc_type in request.types]
    documents: List[Document] = list(await asyncio.gather(*tasks))
    
    # Add dummy literature data if requested
    if request.target_smiles:
        for doc in documents:
            doc.literature = []
            doc.literature_total = 0
    
    return documents
